version: "3.3"
services:
        webserver:
                # image:  webserver
                build:  webserver/
                volumes:
                        - texetvolume:/webserver/instance
                restart:  always
                ports:
                        - "3000:3000"
                env_file:
                        - .env
        fileprocessor:
                # image:  fileprocessor
                build:  fileprocessor/
                volumes:
                        - texetvolume:/webserver/instance
                restart:  always
                env_file:
                        - .env
        imageprocessor:
                # image:  imageprocessor
                build:  imageprocessor/
                volumes:
                        - texetvolume:/webserver/instance
                restart:  always
                env_file:
                        - .env

        cleaner:
                # image:  cleaner
                build:  cleaner/
                volumes:
                        - texetvolume:/webserver/instance
                restart:  always
                env_file:
                        - .env

volumes:
        texetvolume:
              


                      
